apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: errorkube-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ErrorKube is the Schema for the errorkubes API
      displayName: Error Kube
      kind: ErrorKube
      name: errorkubes.errorkube.errorkube.io
      version: v1
  description: error-kube operator
  displayName: error-kube
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - error-kube
  links:
  - name: Errorkube Operator
    url: https://errorkube-operator.domain
  maturity: alpha
  provider:
    name: santhosh
  version: 0.0.0
